### PR TITLE
Bitcoin Cash Orange Styles

### PR DESCRIPTION
**Pull request by maplesyrupsucker**
I was contacted by the folks from BitcoinCash.org who wanted to see the Bitcoin Cash Register app in orange. I left green assets intact in case we want to provide an option to change based on a condition in settings. That switch functionality though might be beyond my android dev capabilities.

Included orange assets, revised xml to use orange and charcoal as per bitcoincash.org. Revised about logo to use official logo

image
image

### CODE REVIEW

**Comment by JavaNoobsyBoobsy** [comment]
It would be better to remove all the green assets (they are already in github anwyay if needed)
All the files under .idea are probably better left uncommitted. Can you please remove them?

**Comment by JavaNoobsyBoobsy** [comment]
Once these changes are done. I will merge & push the latest version on the store. Great work at making the changes.

**Comment by maplesyrupsucker** [comment]
Sure thing - I'll try to remove green assets and we can go from there.

**Comment by Lazhar385** [comment]
good like

**Comment by Jo2530** [comment]
JavaNoobsyBoobsy referenced this pull request from commit 12ef9eb 18 days ago

**Pull request closed without merging**
